#macro nnf global.nnfunctions

/// @desc	Returns any number of requested pegs as an array.
/// @param {Real}	amount	The number of pegs to get.
/// @param {Bool}	unique	Whether or not the same peg can be rolled multiple times.
/// @returns {Array[Id.Instance]}
function nnf_get_random_peg(amount = 1, unique = true) {
	return nnf.get_random_peg(amount, unique);
}

/// @desc	Returns the requested amount of highest # pegs.
/// @param {Real}	amount	The number of pegs to get.
/// @returns {Array[Id.Instance]}
function nnf_get_highest_peg(amount = 1) {
	return nnf.get_highest_peg(amount);
}

/// @desc	Returns the requested amount of lowest # pegs, sorted.
/// @param {Real}	amount	The number of pegs to get.
/// @param {Real}	min_peg_number	Anything below this number will not be returned.
/// @returns {Array[Id.Instance]}
function nnf_get_lowest_peg(amount = 1, min_peg_number = 1) {
	return nnf.get_lowest_peg(amount, min_peg_number);
}

/// @desc	Returns the ID of a given item object.
/// @param {Real}	object	The instance of the item.
/// @returns {Real}
function nnf_get_item_id(object) {
	return nnf.get_item_id(object);
}

/// @desc	Returns the ID of a given perk object.
/// @param {Real}	object	The instance of the perk.
/// @returns {Real}
function nnf_get_perk_id(object) {
	return nnf.get_perk_id(object);
}

/// @desc	Returns the index of the item where -1 is not in the inventory.
/// @param {function}	check_fn	An optional function to check specific attributes of an item.
/// @returns {Real}
function nnf_get_leftmost_item(check_fn = undefined) {
	return nnf.get_leftmost_item(check_fn);
}

/// @desc	Returns the index of the item where -1 is not in the inventory.
/// @param {function}	check_fn	An optional function to check specific attributes of an item.
/// @returns {Real}
function nnf_get_rightmost_item(check_fn = undefined) {
	return nnf.get_rightmost_item(check_fn);
}

/// @desc	Evaluates the result of a random number given against its odds.
/// @param {Real}	random_num	A random number, preferably generated by `random(100)`.
/// @param {Real}	rate		The given rate of that chance happening.
/// @returns {Bool}
function nnf_random_chance(random_num, rate) {
	return nnf.random_chance(random_num, rate);
}

/// @desc	Gives the player a given perk
/// @param {Real}	perk_id	The ID of the desired perk.
/// @param {Real}	at_x	The x coord to spawn it at (defaults to center).
/// @param {Real}	at_y	The y coord to spawn it at (defaults to center).
function nnf_give_perk(perk_id, at_x = 950, at_y = 540) {
	return nnf.give_perk(perk_id, at_x, at_y);
}

/// @desc	Gives the player a suspicious key.
/// @param {Real}	at_x	The x coord to spawn it at (defaults to center).
/// @param {Real}	at_y	The y coord to spawn it at (defaults to center).
function nnf_give_suspicious_key(at_x = 950, at_y = 540) {
	return nnf.give_suspicious_key(at_x, at_y);
}

/// @desc	Gives the player a suspicious key.
/// @param {Real}	amount	How many coins to give.
/// @param {Real}	at_x	The x coord to spawn it at (defaults to center).
/// @param {Real}	at_y	The y coord to spawn it at (defaults to center).
function nnf_give_coins(amount, at_x = 940 + irandom_range(-64, 64), at_y = 563 + irandom_range(-64, 64)) {
	return nnf.give_coins(amount, at_x, at_y);
}

/// @desc	Returns the numerical ID of a specified modded item.
/// @param {String}	modname	The ID name of the mod.
/// @param {String}	name	The ID name of the item.
/// @returns {Real}
function nnf_forgery_get_item_id(modname, name) {
	return nnf.forgery_get_item_id(modname, name);
}

/// @desc	Returns the object index of a specified modded item.
/// @param {String}	modname	The ID name of the mod.
/// @param {String}	name	The ID name of the item.
/// @returns {Asset.GMObject}
function nnf_forgery_get_item_object(modname, name) {
	return nnf.forgery_get_item_object(modname, name);
}

/// @desc	Returns the numerical ID of a specified modded perk.
/// @param {String}	modname	The ID name of the mod.
/// @param {String}	name	The ID name of the perk.
/// @returns {real}
function nnf_forgery_get_perk_id(modname, name) {
	return nnf.forgery_get_perk_id(modname, name);
}

/// @desc	Returns the object index of a specified modded perk.
/// @param {String}	modname	The ID name of the mod.
/// @param {String}	name	The ID name of the perk.
/// @returns {Asset.GMObject}
function nnf_forgery_get_perk_object(modname, name) {
	return nnf.forgery_get_perk_object(modname, name);
}

/// @desc	Returns the numerical ID of a specified modded supervisor.
/// @param {String}	modname	The ID name of the mod.
/// @param {String}	name	The ID name of the supervisor.
/// @returns {real}
function nnf_forgery_get_supervisor_id(modname, name) {
	return nnf.forgery_get_supervisor_id(modname, name);
}

/// @desc	Returns the numerical ID of a specified modded challenge.
/// @param {String}	modname	The ID name of the mod.
/// @param {String}	name	The ID name of the challenge.
function nnf_forgery_get_challenge_id(modname, name) {
	return nnf.forgery_get_challenge_id(modname, name);
}

/// @desc	Returns if the current supervisor is the requested one.
/// @param {String}	modname The string ID of the mod.
/// @param {String}	name	The string ID of the supervisor.
/// @returns {bool}
function nnf_is_supervisor(modname, name) {
	return nnf.is_supervisor(modname, name);
}

/// @desc	Returns if the current challenge is the requested one.
/// @param {String}	modname The string ID of the mod.
/// @param {String}	name	The string ID of the challenge.
/// @returns {bool}
function nnf_is_challenge(modname, name) {
	return nnf.is_challenge(modname, name);
}